apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-csi-app-set
spec:
  selector:
    matchLabels:
      app: mypod
  serviceName: "my-frontend"
  replicas: 1
  template:
    metadata:
      labels:
        app: mypod
    spec:
      containers:
      - name: my-frontend
        image: busybox
        args: ##argumentos que se le pasa al contenerdor 
        - sleep
        - infinity
        volumeMounts: ##declarar un volumen
        - mountPath: "/data" ##path del volumen 
          name: csi-pvc ##nombre del vlumen 
  volumeClaimTemplates: ## se tiene que crear un volumen template
  - metadata:
      name: csi-pvc ##nombre del template del volumen
    spec:
      accessModes: ## Atributo para declarar las caracteristocas 
      - ReadWriteOnce ## que se pueda leer y escribir 
      resources: ## recursos del volumen 
        requests: ## recursos con los que nace el volumen 
          storage: 5Gi ## valor de la memoria que va a ocupar ese volumen 
      storageClassName: do-block-storage  ## driver de kubernetes para un proveedor 