apiVersion: apps/v1
kind: Deployment
metadata:
    name: app2-deployment
spec:
    replicas: 1
    selector: 
        matchLabels:
            chapter: istio
            topic: traffic-magagenet
            app: app2
            version: v2 
    template: 
        metadata: 
            name: app2-pod 
            labels:        
                chapter: istio
                topic: traffic-magagenet
                app: app2
                version: v2
        spec:
            containers:
            - name: app2-container
              image: deepcloud2208/app2:v2
              ports:
              - containerPort: 80         

---
apiVersion: v1
kind: Service
metadata: 
    name: app2-svc
    labels:
        chapter: istio
        topic : traffic-magagenet
        app: app2 
        version: v2
spec:
    type: ClusterIP
    ports:
    - targetPort: 80 
      port: 8080
    selector:
        chapter: istio  
        topic: traffic-magagenet
        app: app2
        version: v2
  