
apiVersion: v1
kind: Service
metadata:
  name: mi-servicio-loadbalancer
spec:
  selector:
    app: prueba
    pod: prueba-pod     
  ports:    
    - port: 80
      targetPort: 80  
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 127.0.0.1